### ISSUE TITLE
ovipets update

### ISSUE THREAD

**Issue by cherryblossomlover** [nodoze313/jovi#4]
with the new update you can no longer mass turn users eggs and mass feed your pets

**Comment by nodoze313** [comment]
This is in progress, hope to get a new version on out this weekend to resolve most of the problems created by the update.

**Comment by cherryblossomlover** [comment]
thank you

**Comment by nodoze313** [comment]
The latest commit should properly turn eggs and feed tabs.

Have not fully tested the always turn and tab switching for feeding.

**Comment by nodoze313** [comment]
The turn all tabs, double click feed, used the old method of finding pets, updated to new.

Everything seems to be working properly now.
